apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-panel
  template:
    metadata:
      labels:
        app: control-panel
    spec:
      containers:
      - name: control-panel
        image: your-dockerhub-username/control-panel:v2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: control-panel-service
spec:
  selector:
    app: control-panel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer